Blog/urls.py
from django.urls import path

from . import views

app_name = 'Blog'

urlpatterns = [
    path('blog', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('signup/',views.signUp, name = 'signup'),
    path('logout/', views.logout_view, name ='logout'),
    path('createblog/', views.blogCreator, name = 'blogCreator'),
    path('listBlog/', views.allBlogs, name= 'allBlogs'),
    path('<int:id>',views.blogDetail),
    path('deleteBlog/<str:id>', views.deleteBlog,name="Blog_delete"),
    path('UpdateBlog/<str:id>',views.updateBlog,name="Blog_update")
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('bookmarks', views.bookmarks, name="bookmarks"),
    path('likes',views.likes, name = "likes")
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('',include('Blog.urls'))
]

Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pengguna(models.Model):
    namalengkap = models.CharField(max_length=100)
    akun = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "{} ".format(self.namalengkap)

class Blog(models.Model):
    judulBlog = models.CharField(max_length=400)
    isiBlog = models.TextField(max_length=20000)
    akun = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return "{} ".format(self.judulBlog)
    

home/models.py
from django.db import models

# Create your models here.

Blog/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class PenggunaForm(forms.ModelForm):
    class Meta :
        model = Pengguna
        fields =['namalengkap']
        labels = {'namalengkap':"Nama Lengkap"}
        widgets ={
            'namalengkap': forms.TextInput(attrs={'class':'form-control','placeholder': "Enter your full name here"})
            }

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['judulBlog','isiBlog']
        judulBlog = forms.CharField(label='Judul Blog')
        isiBlog = forms.CharField(widget=forms.Textarea, label='Isi Blog')


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username",
    widget=forms.TextInput(
        attrs={
        'class' : 'form-control',
        'placeholder' : 'Username',
        'type' : 'text',
        'name': 'username',
    }))

    password = forms.CharField(label="Password", 
    widget=forms.PasswordInput(
        attrs={
        'class' : 'form-control',
        'placeholder' : 'Password',
        'type' : 'password',
        'name': 'password',
    }))

class SignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type' : 'password',
                'placeholder': 'Enter your password',
                'name': 'password',
            }
        )
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type' : 'password',
                'placeholder': 'Confirm your password',
                'name': 'password',
            }
        )
    )
    class Meta :
        model = User
        fields= ("email",'username')
        labels = {'username':'Username','email':'Email',}
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control','placeholder': "Enter your username here",  "autocomplete":"off"}),
            'email': forms.TextInput(attrs={'class':'form-control','placeholder': "Enter your email here",  "autocomplete":"off"}),
        }
        help_texts = {
            "username":None,
        }

Blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
import requests
import json
from .models import *
from .forms import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers

# Create your views here.
def index(request):
    ownBlogs = Blog.objects.all()
    user = request.user
    context = {
        "ownBlog" : ownBlogs,
        "user" : user
    }
    return render(request, 'Blog/blog.html',context)

def allBlogs(request):
    all = Blog.objects.all()
    context ={
        'all':all,
    }
    return render(request, 'Blog/listBlogs.html',context)


def blogCreator(request):
    blog_form = BlogForm()
    blog_model = Blog.objects.all()
    if request.method == 'POST':
        blog_form = BlogForm(request.POST)
        if blog_form.is_valid():
            # blog_form.save()
            blog_model.create(
                judulBlog = blog_form.cleaned_data.get('judulBlog'),
                isiBlog = blog_form.cleaned_data.get('isiBlog'),
                akun = request.user
            )
            print(request.user)
            return redirect('/blog')
    context = {
        'blog_form':blog_form,
        'blog_model':blog_model
    }
    return render(request, 'Blog/blogForum.html',context)




def signUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        form2 = PenggunaForm(request.POST)
        userModel = Pengguna.objects.all()

        if form.is_valid() and form2.is_valid():
            user = form.save()
            userModel.create(
                namalengkap = form2.cleaned_data.get('namalengkap'),
                akun = user
            )
            login(request, user)
            return HttpResponseRedirect('/')

        else:
            for msg in form.error_messages:
                messages.error(request, 'Invalid entry')

    else:
        form = SignUpForm()
        form2 = PenggunaForm()

    context = {
        'form' : form,
        'form2': form2,
    }

    return render(request, "Blog/signup.html", context)

def login_view(request):
    if request.method == 'POST':
        valuenext = request.POST.get('next')
        form = LoginForm(data = request.POST)

        if form.is_valid():
            usernameInput = request.POST["username"]
            passwordInput = request.POST["password"]

            user = authenticate(request, username=usernameInput, password=passwordInput)

            if user is not None and valuenext == "":
                login(request, user)
                return redirect('home:index')
            if user is not None and valuenext != "":
                login(request, user)
                return redirect(valuenext)
        else:
            messages.error(request, 'Invalid entry')

    else:
        form = LoginForm()

    context = {
        'form' : form,
    }

    return render(request, 'Blog/login.html', context)

@login_required
def logout_view(request):
    logout(request)
    form = LoginForm()
    response = {
        'form' : form,
    }
    return redirect('Blog:login')

def blogDetail(request,id):
    blogDetail = Blog.objects.get(id=id)
    context = {
        'blog':blogDetail
    }
    return render(request,'Blog/blogDetail.html',context)

def deleteBlog(request,id):
    item = Blog.objects.get(id=id)
    if request.method == 'POST' :
        item.delete()
        return redirect('/blog')

    return render(request, 'Blog/blogDelete.html',{'item':item})

def updateBlog(request,id):
    blogPilihan = Blog.objects.get(id=id)
    form = BlogForm(instance=blogPilihan)
    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blogPilihan)
        if form.is_valid():
            form.save()
            return redirect('/blog')
    context = {
        'blog_form' :form
    }
    return render (request,'Blog/blogForum.html' ,context)

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core import serializers
# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def bookmarks(request):
    return render(request, 'home/bookmark.html')

def likes(request):
    return render(request, 'home/likes.html')

Blog/templates/Blog/blog.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container-fluid">
    <h1 style="text-align: center; color: #00356B;"><b>List of Your Blogs</b></h1>
    <div style="text-align: right; margin-bottom: 20px;">
        <a class="btn btn-primary" href="{% url 'Blog:blogCreator' %}" role="button">Create New!</a>
    </div>
    {% for i in ownBlog %}
    {% if i.akun == user %}
    <!-- <h1>{{i}}</h1> -->
    <div class="col d-flex justify-content-center">
        <div class="card mb-3" style="max-width: 100rem;">
            <div class="card-header">
                <a href="{{i.id}}">Oleh : {{i.akun}} </a> 
            </div>
            <div class="card-body">
                <h5 class="card-title">{{i.judulBlog}}</h5>
                <p class="card-text">{{i.isiBlog|slice:"0:500"}}...</p>
            </div>
      </div>    
    </div>
    {% endif %}
    {% endfor %}
</div>


{% endblock content %}

Blog/templates/Blog/blogDelete.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Delete Blog</b></h2>
        <hr class="mt-0 mb-4">
        
        <form action="{% url 'Blog:Blog_delete' item.id %}" method='POST'>
            {% csrf_token %}
            <h5 class="featurette-heading">Do you want to delete the course "{{item}}"?</h5>
            <br>
            <button type="submit" class="btn btn-danger"><b>Yes</b></button>
            <a type="button" class="btn btn-info" href="{% url 'Blog:index' %}"><b>Cancel</b></a>

      </div>
    </div>
  </div>
<br>



{% endblock content %}

Blog/templates/Blog/blogDetail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 style="text-align: center; color: #00356B;" class="featurette-heading"><b>Blogs Detail</b></h2>
        <table class="table" style="text-align: left;" >
        <tbody >
          <tr>
            <th scope="row">Judul</th>
            <td>{{ blog.judulBlog }}</td>
          </tr>
          <tr>
            <th scope="row">Isi Blog</th>
            <td>{{ blog.isiBlog|slice:"0:500" }}...</td>
          </tr>
        </tbody>
      </table>
      <a button type="button" class="btn btn-outline-primary" href="{% url 'Blog:Blog_update' blog.id %}">Update Course</a>
      <a class="btn btn-danger" href="{% url 'Blog:Blog_delete' blog.id %}">Delete Course</a>
      <a type="button" class="btn btn-light" href="{% url 'Blog:index' %}"><b>Back</b></a>
  </div>
</div>
</div>


{% endblock content %}

Blog/templates/Blog/blogForum.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container-fluid">
    <div class = "row">
            <div class="col d-flex justify-content-center">
                <h2 style="text-align: center; font-weight: bolder; color: white; font-size: larger;">Blog Creator</h2>
                    <form class="align-self-center" method="POST" >
                       {% csrf_token %}
                        {{ blog_form|crispy }}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                        <button type="submit" class="btn" style="background-color: #2C175D; color: white;" ><b>Submit</b></button>
                    </form>
                </div>
        </div>
    </div>
</div>
<br>
<br>


{% endblock content %}

Blog/templates/Blog/listBlogs.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container-fluid">
    <h2 style="text-align: center; color: #00356B;"><b>Blogs From Others</b></h2>
    {% for i in all %}
    <div class="col d-flex justify-content-center">
        <div class="card mb-3" style="max-width: 100rem;">
            <div class="card-header">Oleh : {{i.akun}}</div>
            <div class="card-body">
                <h5 class="card-title">{{i.judulBlog}}</h5>
                <p class="card-text">{{i.isiBlog|slice:"0:500"}}...</p>
            </div>
      </div>    
    </div>
    {% endfor %}
</div>


{% endblock content %}

Blog/templates/Blog/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}
  
{% block content %}

<div class="container-fluid">
    <div class = "row">
        <div class="col-sm-12">
            <h2 class="text-center" style="margin-top: 20px;"><b>Let's Log In First, Shall We?</b></h2>
            <br>
            <br>
            <div class="col d-flex justify-content-center ">
                <div class="card " style="width: 50rem;">
                    <div class="card-header" style="background-color: #232065;">
                        <p style="text-align: center; font-weight: bolder; color: white; font-size: larger;">LOG IN</p>
                    </div>
                    <div class="card-body">
                        <form class="align-self-center" action="" method="POST">
                            {% csrf_token %}
                            {{ form }}
                            <br>
                            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                            <button style= "background-color: #232065" type="submit" class="btn btn-primary btn-m">Login</button>
                        </form>
                        <p style="margin-top: 10px;">
                            Don't have an account yet? <a class="sign-up-in-link" href="{% url 'Blog:signup' %}"><strong>Sign up.</strong></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Blog/templates/Blog/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container-fluid">
    <div class = "row">
        <div class="col-sm-12">
            <h2 class="text-center" style="margin-top: 20px;"><b>Join Us!</b></h2>
            <br>
            <br>
            <div class="col d-flex justify-content-center">
                <div class="card " style="width: 50rem;">
                    <div class="card-header" style="background-color: #232065;">
                        <p style="text-align: center; font-weight: bolder; color: white; font-size: larger;">SIGN UP</p>
                    </div>
                    <div class="card-body">
                        <form class="align-self-center" action="" method="POST">
                            {% csrf_token %}
                            {{ form }}
                            {{ form2 }}
                            <br>
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                            <button style= "background-color: #232065" type="submit" class="btn btn-primary btn-m">Sign Up</button>
                        </form>
                        <p style="margin-top: 10px;">
                            Already have an existing account? <a class="sign-up-in-link" href="{% url 'Blog:login' %}"><strong>Log in.</strong></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>

{% endblock content %}

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
{% endblock meta %}


{% block content %}
    <div class="container-fluid title">
        <div class="isi-title" >
            <h1 class="pertama">Save Your Favorite Movie 💖</h1>
        </div>
    </div>
    <div class="container-fluid" style="margin-top: 20px;">
        <div>
            <h2 class="label"><b>Search Movie</b></h2>
            <input type="text" id="searchArea" name="fname" placeholder="Movie Title"><br>
            <button style="text-align: right;" type="button" class="searchButton btn btn-dark">Search</button>
            <div class="searching" style="margin-top: 30px; ">
                <h2 class="label"><b>Your Search</b></h2>
                <section id="choosenMovie" style="margin-left: auto; margin-right: auto; ">
                </section>
                <div class="tombol" style="margin-top: 10px;">
                    <button type="button" class="likedButton btn btn-danger">Like</button>
                    <button type="button" class="bookmarkButton btn btn-info">Bookmark</button>
                </div>
            </div>

            <div class="Disukai" style="margin-top: 30px;">
                <h2 class="label"><b>Your Likes</b></h2>
                <section>
                    <div class="row likesClass">
                    </div>
                </section>
            </div>
            
            <div class="Dibookmark" style="margin-top: 30px;">
                <h2 class="label"><b>Your Bookmarks</b></h2>
                <section >
                    <div class="row bookmarksClass">
                    </div>
                </section>
            </div>
            <section id="popularMovies">
            </section>
        </div>
    </div>
    
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!-- font awesome  -->
        <script src="https://kit.fontawesome.com/fb1ce7db1a.js" crossorigin="anonymous"></script>
        <!-- AJAX  -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        
        <!-- CSS & Bootstrap  -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

          <!-- font  -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;900&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">

        <title>Movie</title>
    </head>
    
    <div class="container-fluid title">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="/" >RISTEK</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a style="color: white; " class="nav-link" href="{% url 'Blog:allBlogs' %}">Blog</a></li>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a style="color: white; " class="nav-link" href="{% url 'Blog:index' %}">Hello, {{ request.user }}</a></li>
            </li>
            <!-- Log out  -->
            <li class="nav-item">
              <a style="color: white; font-weight: bold" class="nav-link" href="{% url 'Blog:logout' %}">Logout</a></li>
            </li>
            {% else %}
            <!-- Login -->
            <li class="nav-item">
              <a style="color: white" class="nav-link" href="{% url 'Blog:login' %}">Login</a></li>
            </li>
            <!-- Register -->
            <li class="nav-item">
              <a style="color: white;" class="nav-link" href="{% url 'Blog:signup' %}">Register</a></li>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    {% block meta %}
    {% endblock meta %}
<body>
  <section id="title">

  {% block content %}
  {% endblock content %}
</body>
</html>